paxos_config = "paxos.conf"
requests_path = "workloada.csv"
repartition_method = "ROUND_ROBIN"
repartition_interval = 5000000
proposer_id = 0
print_percentage = 0
n_partitions = 8
n_checkpointers = 1
n_dispatchers_threads = 1
n_initial_keys = 0
n_requests = 50000000
