paxos_config = "paxos.conf"
requests_path = "workloadd.csv"
repartition_method = "METIS"
repartition_interval = 32000000
proposer_id = 0
print_percentage = 0
n_partitions = 8
n_checkpointers = 8
n_dispatchers_threads = 1
n_initial_keys = 10000000
n_requests = 0
