paxos_config = "paxos.conf"
requests_path = "workloade.csv"
repartition_method = "METIS"
repartition_interval = 840000
proposer_id = 0
print_percentage = 0
n_partitions = 8
n_checkpointers = 8
n_dispatchers_threads = 1
n_initial_keys = 2320000
n_requests = 0
